baseURL = '/'
languageCode = 'en-us'
title = 'Jakiya Hussain'
theme = 'paper'

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  # twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  github = 'riyahussain'                    # github.com/YOUR_GITHUB_ID
  linkedin = 'in/jakiya'
  

  # home page profile
  avatar = 'jakiya.h97@outlook.com'         # gravatar email or image url
  name = 'Hey, Iâ€™m Jakiya ğŸ‘‹ğŸ½'
  bio = 'A Data Analyst from the UK. Check out some of my projects below!'
  
  # misc
  monoDarkIcon = true                       # show monochrome dark mode icon

  dateFormat = '02 Jan 2006'

[menu]

 # [[menu.main]]
    #identifier = "about"
    #name = "About"
    #url = "/about/"
    #weight = 10
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv.pdf"
    weight = 10